// PromptRFA/DeskProcessor.cs
using System;
using System.IO;
using System.Linq;
using System.Text.Json;
using Autodesk.Revit.ApplicationServices;
using Autodesk.Revit.DB;

namespace PromptRFA
{
    // JSONデータ定義
    public class FamilyParameters
    {
        public double Width { get; set; }
        public double Depth { get; set; }
        public double Height { get; set; }
        public string Name { get; set; }
    }

    public class DeskProcessor
    {
        // パス設定 (環境に合わせて変更してください)
        private const string BASE_DIR = @"C:\Users\81805\StudioProjects\prompt_rfa";
        private const string JSON_PATH = BASE_DIR + @"\params.json";
        private const string OUTPUT_DIR = BASE_DIR + @"\OutputFamilies";
        private const string TEMPLATE_PATH = @"C:\ProgramData\Autodesk\RVT 2025\Family Templates\Japanese\一般モデル(メートル単位).rft";

        // メイン処理の入り口
        public void Run(Application app)
        {
            Logger.Write("Config: JSON読み込み開始...");

            double w = 1000.0, d = 1000.0, h = 700.0;
            string famName = "AutoGenerated";

            // 1. JSON読み込み
            try
            {
                if (!File.Exists(JSON_PATH))
                {
                    Logger.Write($"Error: JSONが見つかりません: {JSON_PATH}");
                    return;
                }
                string jsonString = File.ReadAllText(JSON_PATH);
                var p = JsonSerializer.Deserialize<FamilyParameters>(jsonString);
                if (p != null)
                {
                    w = p.Width; d = p.Depth; h = p.Height;
                    if (!string.IsNullOrEmpty(p.Name)) famName = p.Name;
                }
            }
            catch (Exception ex)
            {
                Logger.Write($"Error: JSON読み込み失敗: {ex.Message}");
                return;
            }

            // 2. テンプレート確認
            if (!File.Exists(TEMPLATE_PATH))
            {
                Logger.Write("Error: テンプレートが見つかりません。");
                return;
            }

            // 3. ドキュメント作成
            Document familyDoc = app.NewFamilyDocument(TEMPLATE_PATH);
            if (familyDoc == null) return;

            // 4. トランザクション実行（形状作成）
            using (Transaction t = new Transaction(familyDoc, "Create Desk"))
            {
                t.Start();
                try
                {
                    double wFt = UnitUtils.ConvertToInternalUnits(w, UnitTypeId.Millimeters);
                    double dFt = UnitUtils.ConvertToInternalUnits(d, UnitTypeId.Millimeters);
                    double hFt = UnitUtils.ConvertToInternalUnits(h, UnitTypeId.Millimeters);

                    CreateDeskGeometry(familyDoc, wFt, dFt, hFt);
                    t.Commit();
                }
                catch (Exception ex)
                {
                    Logger.Write($"Error: 作成中にエラー: {ex.Message}");
                    t.RollBack();
                    familyDoc.Close(false);
                    return;
                }
            }

            // 5. 保存
            if (!Directory.Exists(OUTPUT_DIR)) Directory.CreateDirectory(OUTPUT_DIR);
            string savePath = Path.Combine(OUTPUT_DIR, famName + "_v2.rfa");
            SaveAsOptions opt = new SaveAsOptions { OverwriteExistingFile = true };

            try
            {
                familyDoc.SaveAs(savePath, opt);
                Logger.Write($"Success: 保存成功 -> {savePath}");
                familyDoc.Close(false);
            }
            catch (Exception ex)
            {
                Logger.Write($"Error: 保存失敗: {ex.Message}");
                familyDoc.Close(false);
            }
        }

        // 机の形状作成ロジック
        private void CreateDeskGeometry(Document doc, double width, double depth, double height)
        {
            double legSize = UnitUtils.ConvertToInternalUnits(50, UnitTypeId.Millimeters);
            double topThickness = UnitUtils.ConvertToInternalUnits(30, UnitTypeId.Millimeters);
            double legHeight = height - topThickness;

            // 天板
            CreateCuboid(doc, 0, 0, width, depth, height, height - topThickness);

            // 脚4本
            double legOffsetX = (width / 2.0) - (legSize / 2.0);
            double legOffsetY = (depth / 2.0) - (legSize / 2.0);

            CreateCuboid(doc, legOffsetX, -legOffsetY, legSize, legSize, legHeight, 0);
            CreateCuboid(doc, -legOffsetX, -legOffsetY, legSize, legSize, legHeight, 0);
            CreateCuboid(doc, legOffsetX, legOffsetY, legSize, legSize, legHeight, 0);
            CreateCuboid(doc, -legOffsetX, legOffsetY, legSize, legSize, legHeight, 0);

            Logger.Write("Action: 机の形状を作成しました。");
        }

        // 直方体作成ヘルパー
        private void CreateCuboid(Document doc, double centerX, double centerY, double w, double d, double topLevel, double baseOffset)
        {
            double w2 = w / 2.0;
            double d2 = d / 2.0;

            XYZ p0 = new XYZ(centerX - w2, centerY - d2, 0);
            XYZ p1 = new XYZ(centerX + w2, centerY - d2, 0);
            XYZ p2 = new XYZ(centerX + w2, centerY + d2, 0);
            XYZ p3 = new XYZ(centerX - w2, centerY + d2, 0);

            CurveArray curveArray = new CurveArray();
            curveArray.Append(Line.CreateBound(p0, p1));
            curveArray.Append(Line.CreateBound(p1, p2));
            curveArray.Append(Line.CreateBound(p2, p3));
            curveArray.Append(Line.CreateBound(p3, p0));

            CurveArrArray curveArrArray = new CurveArrArray();
            curveArrArray.Append(curveArray);

            FilteredElementCollector levelCollector = new FilteredElementCollector(doc);
            var levels = levelCollector.OfClass(typeof(Level)).ToElements();
            Level targetLevel = levels.FirstOrDefault(e => e.Name == "参照レベル") as Level;
            if (targetLevel == null) targetLevel = levels.FirstOrDefault(e => e.Name == "Ref. Level") as Level;
            if (targetLevel == null) targetLevel = levels.FirstOrDefault() as Level;

            SketchPlane sketchPlane = SketchPlane.Create(doc, targetLevel.Id);
            
            // NewExtrusionの高さは「厚み」を指定
            double extrusionHeight = topLevel; 
            Extrusion ext = doc.FamilyCreate.NewExtrusion(true, curveArrArray, sketchPlane, extrusionHeight);
            
            // 下端のオフセット設定
            if (baseOffset > 0)
            {
                Parameter startParam = ext.get_Parameter(BuiltInParameter.EXTRUSION_START_PARAM);
                if (startParam != null) startParam.Set(baseOffset);
            }
        }
    }
}