import React from "react";

export default function TermsPage() {
  return (
    <div className="container max-w-3xl py-10 px-6">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      <div className="prose prose-slate dark:prose-invert">
        <p className="mb-4 text-sm text-muted-foreground">
          Effective Date: 2026-01-11
        </p>

        <p>
          These Terms of Service (hereinafter referred to as the
          &quot;Terms&quot;) set forth the terms and conditions for the use of
          the service &quot;Archifields&quot; (hereinafter referred to as the
          &quot;Service&quot;) provided by Mulberryfields.
          (hereinafter referred to as the &quot;Company&quot;).
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-4">
          Article 1 (Applicability)
        </h2>
        <p>
          These Terms shall apply to all relationships related to the use of the
          Service between the user and the Company.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-4">
          Article 2 (Disclaimer regarding Generated Data)
        </h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            The Service generates Revit family data (RFA format) and other
            related data using Artificial Intelligence (AI) and automated design
            programs.
          </li>
          <li>
            The Company makes <strong>no warranties</strong> regarding the
            accuracy, completeness, fitness for a particular purpose, or
            structural/architectural safety of the data generated by the Service
            (hereinafter referred to as &quot;Generated Data&quot;).
          </li>
          <li>
            Users agree to use the Generated Data for actual construction or
            design work only after verifying and modifying it based on their own
            professional knowledge and responsibility. The Company shall not be
            liable for any damages arising from the use of the Generated Data.
          </li>
        </ul>

        <h2 className="text-xl font-semibold mt-8 mb-4">
          Article 3 (Prohibited Acts)
        </h2>
        <p>
          Users shall not engage in the following acts when using the Service:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            Acts that violate laws, regulations, or public order and morals.
          </li>
          <li>
            Acts that interfere with or disrupt the functions of the
            Company&apos;s servers or networks.
          </li>
          <li>
            Acts of collecting or accumulating personal information of other
            users.
          </li>
          <li>Acts of impersonating other users.</li>
        </ul>

        <h2 className="text-xl font-semibold mt-8 mb-4">
          Article 4 (Changes to Service)
        </h2>
        <p>
          The Company may change the contents of the Service or discontinue the
          Service without notifying the user, and shall not be liable for any
          damages caused to the user by such actions.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-4">
          Article 5 (Governing Law and Jurisdiction)
        </h2>
        <p>
          These Terms shall be governed by and construed in accordance with the
          laws of Japan. Any disputes arising out of or in connection with the
          Service shall be subject to the exclusive agreed jurisdiction of the
          courts having jurisdiction over the location of the Company&apos;s
          head office.
        </p>
      </div>
    </div>
  );
}
